한줄 리뷰, 장문 리뷰 api 추가
oduck-team/oduck-server-nestjs pull request #14
Opened 2023-08-15 14:25 UTC by yunhozz

## 📝 개요

한줄 리뷰: 무한 스크롤 조회, 생성, 삭제 api
장문 리뷰: 무한 스크롤 조회, 단건 조회, 생성, 수정, 삭제 api

## 🚀 변경사항

`prismaService`에서 쿼리를 로그로 남기기 위해 `configService`를 이용해 보았습니다.

![image](https://github.com/oduck-team/oduck-server/assets/95674746/d3098430-a694-42a5-be95-5b3488a18d54)

## 🔗 관련 이슈

#8

## ➕ 기타

1. `prismaService`를 global에서 모듈로 관리해서 주입할지, 단순히 선언(?)으로 import 할지 정해야 할 것 같아요.
2. 각 api의 응답을 통일해야 할 것 같아요. 한줄 리뷰 api는 response dto 스타일로, 장문 리뷰 api는 따로 dto 사용하지 않았습니다.
3. 각 리뷰에 대해 사용자의 이름, 닉네임, 프로필 사진이 필요해서 member 도메인이 완성되면 수정할게요.
4. jest를 이용한 테스트를 아직 진행하지 않았습니다. 이에 대해 공부 좀 더 하고 구조나 스타일을 통일한 후 진행할게요ㅎㅎ
5. 기타 TODO 리스트입니다.
![image](https://github.com/oduck-team/oduck-server/assets/95674746/95f8ff5c-2255-457c-ae2f-1ac32e8277b6)

2023-08-17 13:49 UTC, FaberJoo commented on src/global/config/prisma/prisma.service.ts
> +
쿼리 보여주는 설정 너무 좋은 것 같습니다 👍

2023-08-17 13:49 UTC, FaberJoo commented on src/domain/review/controller/short-review.controller.ts
> +  @TypedRoute.Patch('/:id/delete')
소프트 딜리트에 patch method를 사용하시는 이유가 있을까요?

2023-08-17 14:06 UTC, yunhozz commented on src/domain/review/controller/short-review.controller.ts
> +  @TypedRoute.Patch('/:id/delete')
수정했습니다 ㅎㅎ!

2023-08-17 17:30 UTC, sunday00 requested changes
conflict만 해결하고 일단 머지해도  될 거 같습니다. 일단은 초반은 스키마, 폴더구조 등 바뀌는게 많아서 놓지면 지지부진해질거 같고 일단 먼저 빠르게 합치고 써보고 변경할때 합의해서 또 같이 변경하고 하시져~

2023-08-17 17:30 UTC, sunday00 commented on src/domain/review/reviews.repository.ts
> +        type: 'SHORT',
그 type 부분에 enum 있다 아닌가유?

2023-08-17 17:30 UTC, sunday00 commented on src/domain/review/reviews.repository.ts
> +    return shortReview;
map 안에 callback 은 async await 안되서 이렇게 하신거 같은데 걍 for of 돌리는게 낫지 않겠나 싶습니다.

2023-08-17 23:37 UTC, yunhozz commented on src/domain/review/reviews.repository.ts
> +    return shortReview;
`for of`으로 `await`를 하나씩 돌리는 것 보단 `Promise.all()`으로 한번에 처리하는 쪽이 속도 면에서 더 좋을 것 같아서 사용해 봤습니다. 물론 개수가 적어서 유의미한 효과는 없겠네요ㅎㅎ

2023-08-18 01:51 UTC, yunhozz commented on src/domain/review/reviews.repository.ts
> +        type: 'SHORT',
prisma query 부분에는 enum 잘 써놓고 여기서 실수했네요ㅎㅎ;
수정 완료했습니다. 감사합니다.

2023-08-21 12:50 UTC, sunday00 approved these changes

2023-08-21 12:50 UTC, sunday00 commented on src/domain/review/reviews.repository.ts
> +    return shortReview;
비동기 처리 땜에요? 그럼 map 안쪽에 async await 이 필요 한가요?

2023-08-21 12:50 UTC, FaberJoo approved these changes
🚀

2023-08-23 14:45 UTC, merged